markdown: kramdown
highlighter: rouge
permalink: '/:title'
google_analytics: UA-40719525-1

kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

title: Rants on Software Development
description: > # this means to ignore newlines until "show_excerpts:"
  Personal website and rants about software development from Rafael Revi.
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: solarized
  social_links:
    - { platform: github,  user_url: "https://github.com/rrevi" }
    - { platform: linkedin,  user_url: "https://linkedin.com/in/rafaelrevi" }
  date_format: "%Y-%m-%d" # http://shopify.github.io/liquid/filters/date/

remote_theme: jekyll/minima

paginate: 4

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
